FROM mariadb:lts

ENV MARIADB_ROOT_PASSWORD demo_pass

# These files can become huge, gigabytes
# See: https://github.com/sagemathinc/cocalc/issues/2287
RUN rm /var/log/faillog /var/log/lastlog

COPY initdb.d docker-entrypoint-initdb.d
COPY files/mariadb.cnf /etc/mysql/mariadb.conf.d/51-server.cnf

HEALTHCHECK --timeout=5s --retries=12 \
    CMD mariadb-admin -uroot -pdemo_pass ping | grep alive
